```{r}
library(htmltab)
library(stringr) 
library(readr)
```

```{r}
lkCSV="https://github.com/tpolicio/meepo01/raw/master/efectividad2016.csv"
efectividad=import(lkCSV)
```

```{r}
lkCSV="https://github.com/tpolicio/meepo01/raw/master/desempleo2016-1.csv"
desempleo=import(lkCSV)
```

```{r}
desempleo=desempleo[,-c(1,2,4)]
```

```{r}
efectividad=efectividad[,-c(2:4)]
```

```{r}
str(desempleo)
str(efectividad)
```

```{r}
names(desempleo)= c("pais","Des2016")
names(efectividad)= c("pais", "Efec2016")
```

```{r}
head(desempleo)
head(efectividad)
```

```{r}
desempleo=desempleo[-c(218:222),]
efectividad=efectividad[-c(215:219),]
```

```{r}
desempleo[,c(2)]=as.numeric(desempleo[,c(2)])
efectividad[,c(2)]=as.numeric(efectividad[,c(2)])
```
#Se eliman las N.A
```{r}
desempleo=na.omit(desempleo)
efectividad=na.omit(efectividad)

```



```{r}
variable1= merge(desempleo, efectividad, by.x = "pais", by.y = "pais")
```

```{r}
str(variable1)
```

```{r}
variable1[,c(2)]=as.numeric(variable1[,c(2)])
variable1[,c(3)]=as.numeric(variable1[,c(3)])
```

```{r}
variable1=na.omit(variable1)
```
