```{r}
library(htmltab)
library(stringr) 
library(readr)
```

```{r}
lkCSV="https://github.com/tpolicio/meepo01/raw/master/efectividad2016.csv"
efectividad=import(lkCSV)
```

```{r}
lkCSV="https://github.com/tpolicio/meepo01/raw/master/desempleo2016-1.csv"
desempleo=import(lkCSV)
```

```{r}
desempleo=desempleo[,-c(1,2,4)]
```

```{r}
efectividad=efectividad[,-c(2:4)]
```

```{r}
str(desempleo)
str(efectividad)
```

```{r}
names(desempleo)= c("Pais","Des2016")
names(efectividad)= c("Pais", "Efec2016")
```

```{r}
head(desempleo)
head(efectividad)
```

```{r}
desempleo=desempleo[-c(218:222),]
efectividad=efectividad[-c(215:219),]
```

```{r}
desempleo[,c(2)]=as.numeric(desempleo[,c(2)])
efectividad[,c(2)]=as.numeric(efectividad[,c(2)])
```

```{r}
desempleo=na.omit(desempleo)
efectividad=na.omit(efectividad)
```



```{r}
merge.desm.efec= merge(desempleo, efectividad, by.x = "Pais", by.y = "Pais")
```

```{r}
str(merge.desm.efec)
```

```{r}
merge.desm.efec[,c(2)]=as.numeric(merge.desm.efec[,c(2)])
merge.desm.efec[,c(3)]=as.numeric(merge.desm.efec[,c(3)])
```

```{r}
merge.desm.efec=na.omit(merge.desm.efec)
```